export const BALANCE = {
  saveKey: "stellar-genesis-save-v1",
  saveVersion: 1,
  baseClickPower: 1,
  firstUpgradeCost: 12,
  upgradeCostMultiplier: 1.15,
  planetCostBase: 200,
  planetCostMultiplier: 1.75,
  evolveBaseCost: 120,
  evolveCostMultiplier: 1.8,
  specializationBaseCost: 220,
  researchBaseCost: 300,
  automationBaseCost: 420,
  prestigeThreshold: 1_000_000,
  offlineCapHours: 8,
  offlineEfficiency: 0.75,
  maxPlanets: 4,
  eventCooldownMinMs: 180_000,
  eventCooldownMaxMs: 480_000,
  startingStarClass: "yellow-dwarf",
};
